name: stackit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  http: ^1.2.1
  local_auth: ^2.3.0
  flutter_quill: ^11.4.1
  flutter_localizations:
    sdk: flutter
  # Optional - Uncomment if/when needed
  # qr_code_scanner_plus: ^2.0.10+1
  # audioplayers: ^5.2.1
  # razorpay_flutter: ^1.3.5
  # fluttertoast: ^8.2.4
  # pdf: ^3.11.3
  # printing: ^5.14.2
  # qr_flutter: ^4.1.0
  # crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/images/loginimage.png
    # - assets/images/kurkure.webp
